config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
    }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :products do
        member do
            post :add_to_cart
        end
    end
    namespace :admin do
        resources :infos
        resources :products
        resources :orders do
            member do
                post :cancel
                post :ship
                post :shipped
                post :return
            end
        end
    end
    root 'welcome#index'
    resources :infos do
        resources :posts
    end
    resources :posts
    resources :carts do
        collection do
            delete :clean
            post :checkout
        end
    end
    resources :cart_items

    resources :orders do
        member do
            post :pay_with_alipay
            post :pay_with_wechat
            post :apply_to_cancel
        end
    end
    namespace :account do
        resources :orders
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :products, through: :cart_items, source: :product

    def add_product_to_cart(product)
        ci = cart_items.build
        ci.product = product
        ci.quantity = 1
        ci.save
    end

    def total_price
        sum = 0
        cart_items.each do |cart_item|
            if cart_item.product.price.present?
                sum += cart_item.quantity * cart_item.product.price
            end
        end
        sum
    end

    def clean!
        cart_items.destroy_all
    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/info.rb
class Info < ApplicationRecord
    has_many :posts
    belongs_to :user, optional: true
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    before_create :generate_token

    def generate_token
        self.token = SecureRandom.uuid
    end
    has_many :productlists
    belongs_to :user
    validates :billing_name, presence: true
    validates :billing_address, presence: true
    validates :shipping_address, presence: true
    validates :shipping_name, presence: true

    scope :recent, -> { order('created_at DESC') }

    def set_payment_with!(method)
        update_columns(payment_method: method)
    end

    def pay!
        update_columns(is_paid: true)
    end

    include AASM

    aasm do
        state :order_placed, initial: true
        state :paid
        state :shipping
        state :shipped
        state :order_cancelled
        state :good_returned

        event :make_payment, after_commit: :pay! do
            transitions from: :order_placed, to: :paid
        end

        event :ship do
            transitions from: :paid, to: :shipping
        end

        event :deliver do
            transitions from: :shipping, to: :shipped
        end

        event :return_good do
            transitions from: :shipped, to: :good_returned
        end

        event :cancel_order do
            transitions from: [:order_placed, :paid], to: :order_cancelled
        end
    end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :info, optional: true
    belongs_to :user, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/productlist.rb
class Productlist < ApplicationRecord
    belongs_to :order, optional: true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    def admin?
        is_admin
    end
    has_many :orders

    has_many :posts
    has_many :infos
end

app/controllers/account/orders_controller.rb
class Account::OrdersController < ApplicationController
    before_action :authenticate_user!

    def index
        @orders = current_user.orders.recent
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    layout 'admin'
    before_action :authenticate_user!
    before_action :required_is_admin

    def index
        @orders = Order.order('id DESC')
    end

    def show
        @order = Order.find(params[:id])
        @productlists = @order.productlists
    end

    def ship
        @order = Order.find(params[:id])
        @order.ship!
        OrderMailer.notify_ship(@order).deliver!
        redirect_to :back
    end

    def shipped
        @order = Order.find(params[:id])
        @order.deliver!
        redirect_to :back
    end

    def cancel
        @order = Order.find(params[:id])
        @order.cancel_order!
        OrderMailer.notify_cancel(@order).deliver!

        redirect_to :back
    end

    def return
        @order = Order.find(params[:id])
        @order.return_good!
        redirect_to :back
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def clean
        current_cart.clean!
        flash[:warning] = '已清空购物车'
        redirect_to carts_path
    end

    def checkout
        @order = Order.new
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!
    def show
        @order = Order.find_by_token(params[:id])
        @productlists = @order.productlists
    end

    def create
        @order = Order.new(order_params)
        @order.user = current_user
        @order.total = current_cart.total_price

        if @order.save
            current_cart.cart_items.each do |cart_item|
                productlist = Productlist.new
                productlist.order = @order
                productlist.product_name = cart_item.product.title
                productlist.product_price = cart_item.product.price
                productlist.quantity = cart_item.quantity
                productlist.save
            end
            current_cart.clean!
            OrderMailer.notify_order_placed(@order).deliver!
            redirect_to order_path(@order.token)
        else
            render :checkout
        end
    end

    def pay_with_alipay
        @order = Order.find_by_token(params[:id])
        @order.set_payment_with!('alipay')
        @order.make_payment!
        redirect_to order_path(@order.token), notice: '使用支付宝已成功付款'
    end

    def pay_with_wechat
        @order = Order.find_by_token(params[:id])
        @order.set_payment_with!('wechat')
        @order.make_payment!
        redirect_to order_path(@order.token), notice: '使用微信已成功付款'
    end

    def apply_to_cancel
        @order = Order.find(params[:id])
        OrderMailer.apply_cancel(@order).deliver!
        flash[:notice] = '已提交申请'
        redirect_to :back
    end

    private

    def order_params
        params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
    end
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
    def render_order_paid_state(order)
        if order.is_paid?
            '已付款'
        else
            '未付款'
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
    def render_cart_total_price(cart)
        cart.total_price
    end
end

app/helpers/flashes_helper.rb
module FlashesHelper
    FLASH_CLASSES = { alert: 'danger', notice: 'success', warning: 'warning' }.freeze
    def flash_class(key)
        FLASH_CLASSES.fetch key.to_sym, key
    end

    def user_facing_flashes
        flash.to_hash.slice 'alert', 'notice', 'warning'
    end
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/orders/_state_option.html.erb
<div style="padding:10px; float:right;">
    <% case order.aasm_state %>
    <% when "order_placed"%>
    <%= link_to("取消订单",cancel_admin_order_path(order), class: "btn btn-default btn-sm", method: :post)%>
    <% when "paid"%>
    <%= link_to("取消订单",cancel_admin_order_path(order), class: "btn btn-default btn-sm", method: :post)%>
    <%= link_to("出货",ship_admin_order_path(order), class: "btn btn-default btn-sm", method: :post)%>
    <% when "shipping"%>
    <%= link_to("设为已出货",shipped_admin_order_path(order), class: "btn btn-default btn-sm", method: :post)%>
    <% when "shipped"%>
    <%= link_to("退货",return_admin_order_path(order), class: "btn btn-default btn-sm", method: :post)%>
    <% when "order_cancelled"%>
    <span class="label label-default">订单已取消</span>
    <% when "good_returned"%>
    <span class="label label-default">已退货</span>
<% end %>
</div>

app/views/admin/orders/index.html.erb
<h2>订单列表</h2>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>生成时间</th>
            <th>订购者</th>
            <th>订单状态</th>
        </tr>
    </thead>
    <tbody>
        <% @orders.each do |order|%>
            <tr>
                <td><%= link_to(order.id, admin_order_path(order))%></td>
                <td><%= order.created_at.to_s(:long) %></td>
                <td><%= order.user.email %></td>
                <td><%= order.aasm_state%></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/admin/orders/show.html.erb
<div class="row">
    <div class="col-md-12">
        <h2>订单明细(<%= render_order_paid_state(@order)%>)</h2>
        <%= render "admin/orders/state_option", order: @order %>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>商品明细</th>
                    <th>单价</th>
                    <th>数量</th>
                </tr>
            </thead>
            <tbody>
                <% @productlists.each do |productlist|%>
                    <tr>
                        <td><%= productlist.product_name%></td>
                        <td><%= productlist.product_price%></td>
                        <td><%= productlist.quantity%></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <div class="total clearfix">
            <span class="pull-right">
                总计<%= @order.total%>CNY
      </span>
        </div>
        <hr>
        <h2>寄送资讯</h2>
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td>订购人</td>
                </tr>
                <tr>
                    <td><%= @order.billing_name%>-<%= @order.billing_address%></td>
                </tr>
                <tr>
                    <td>收件人</td>
                </tr>
                <tr>
                    <td><%= @order.shipping_name%>-<%= @order.shipping_address%></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>