config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
    }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :products do
        member do
            post :add_to_cart
        end
    end
    namespace :admin do
        resources :infos
        resources :products
        resources :orders do
            member do
                post :cancel
                post :ship
                post :shipped
                post :return
            end
        end
    end
    root 'welcome#index'
    resources :infos do
        resources :posts
    end
    resources :posts
    resources :carts do
        collection do
            delete :clean
            post :checkout
        end
    end
    resources :cart_items

    resources :orders do
        member do
            post :pay_with_alipay
            post :pay_with_wechat
            post :apply_to_cancel
        end
    end
    namespace :account do
        resources :orders
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :products, through: :cart_items, source: :product

    def add_product_to_cart(product)
        ci = cart_items.build
        ci.product = product
        ci.quantity = 1
        ci.save
    end

    def total_price
        sum = 0
        cart_items.each do |cart_item|
            if cart_item.product.price.present?
                sum += cart_item.quantity * cart_item.product.price
            end
        end
        sum
    end

    def clean!
        cart_items.destroy_all
    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/info.rb
class Info < ApplicationRecord
    has_many :posts
    belongs_to :user, optional: true
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    before_create :generate_token

    def generate_token
        self.token = SecureRandom.uuid
    end
    has_many :productlists
    belongs_to :user
    validates :billing_name, presence: true
    validates :billing_address, presence: true
    validates :shipping_address, presence: true
    validates :shipping_name, presence: true

    scope :recent, -> { order('created_at DESC') }

    def set_payment_with!(method)
        update_columns(payment_method: method)
    end

    def pay!
        update_columns(is_paid: true)
    end

    include AASM

    aasm do
        state :order_placed, initial: true
        state :paid
        state :shipping
        state :shipped
        state :order_cancelled
        state :good_returned

        event :make_payment, after_commit: :pay! do
            transitions from: :order_placed, to: :paid
        end

        event :ship do
            transitions from: :paid, to: :shipping
        end

        event :deliver do
            transitions from: :shipping, to: :shipped
        end

        event :return_good do
            transitions from: :shipped, to: :good_returned
        end

        event :cancel_order do
            transitions from: [:order_placed, :paid], to: :order_cancelled
        end
    end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :info, optional: true
    belongs_to :user, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/productlist.rb
class Productlist < ApplicationRecord
    belongs_to :order, optional: true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    def admin?
        is_admin
    end
    has_many :orders

    has_many :posts
    has_many :infos
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    before_action :authenticate_user!
    before_action :required_is_admin
    layout 'admin'
    def index
        @products = Product.all
      end

    def show
        @product = Product.find(params[:id])
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            redirect_to admin_products_path
        else
            render :new
        end
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to admin_products_path
            flash[:notice] = 'Update Success'
        else
            render :edit
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to admin_products_path
    end

    private

    def product_params
        params.require(:product).permit(:title, :description, :price, :quantity, :image)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def clean
        current_cart.clean!
        flash[:warning] = '已清空购物车'
        redirect_to carts_path
    end

    def checkout
        @order = Order.new
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end

    def add_to_cart
        @product = Product.find(params[:id])
        if !current_cart.products.include?(@product)
            current_cart.add_product_to_cart(@product)
            flash[:notice] = '成功加入购物车'
        else
            flash[:notice] = "你已成功将#{@product.title}加入到购物车"
        end
        redirect_to :back
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
    def render_cart_total_price(cart)
        cart.total_price
    end
end

app/helpers/flashes_helper.rb
module FlashesHelper
    FLASH_CLASSES = { alert: 'danger', notice: 'success', warning: 'warning' }.freeze
    def flash_class(key)
        FLASH_CLASSES.fetch key.to_sym, key
    end

    def user_facing_flashes
        flash.to_hash.slice 'alert', 'notice', 'warning'
    end
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/products/edit.html.erb
<h3> edit a product</h3>
<%= simple_form_for [:admin,@product] do |f|%>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price%>
    <%= f.input :quantity %>
    <% if @product.image.present?%>
        <span>目前商品图</span><br>
        <%= image_tag(@product.image.thumb.url)%>
    <% end %>
    <%= f.input :image, as: :file %>
    <%= f.submit 'Submit' %>
<% end %>

app/views/admin/products/index.html.erb
<h3>Product List</h3>
<%= link_to("Add new product", new_admin_product_path, class: "btn btn-default pull-right")%>
<table class="table table-boldered">
    <thead>
        <tr>
            <th>#</th>
            <th>图片</th>
            <th>品名</th>
            <th>价格</th>
            <th>选项</th>
        </tr>
    </thead>
    <tbody>
        <% @products.each do |product|%>
            <tr>
                <td><%= product.id %></td>
                <td><%= link_to admin_product_path(product) do %>
                        <% if product.image.present?%>
                            <%= image_tag(product.image.thumb.url, class: "thumbnail")%>
                        <% else %>
                            <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail")%>
                        <% end %>
                    <% end %>
                </td>
                <td><%= product.title%></td>
                <td><%= product.price %></td>
                <td><%= link_to("Edit",edit_admin_product_path(product))%>
                    <%= link_to("delete",admin_product_path(product),method: :delete, :data =>{:confirm =>"Are you sure?"})%>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/admin/products/new.html.erb
<h3> add a product</h3>
<%= simple_form_for [:admin,@product] do |f|%>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price%>
    <%= f.input :quantity %>
    <%= f.input :image, as: :file %>
    <%= f.submit 'Submit' %>
<% end %>

app/views/admin/products/show.html.erb
<h2><%= @product.title %></h2>
<div >
    <% if @product.image.present? %>
        <%= image_tag(@product.image.thumb.url)%>
    <% else %>
        <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
    <% end %>
</div>
<div style="height:100px;">
    <%= @product.description%>
</div>
<div >
    数量：  <%= @product.quantity%>
</div>
<div >
    <%= @product.price %>
</div>

app/views/products/index.html.erb
<div class="row">
    <% @products.each do |product| %>
        <div class="col-xs-6 col-md-3">
            <%= link_to product_path(product) do%>
                <% if product.image.present? %>
                    <%= image_tag(product.image.thumb.url, class: "thumbnail")%>
                <% else %>
                    <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail")%>
                <% end %>
            <% end %>
            <%= product.title %>¥<%= product.price%>
        </div>
    <% end %>
</div>

app/views/products/show.html.erb
<div class="row">
    <div class="col-md-6">
        <h2><%= @product.title %></h2>
        <div >
            <% if @product.image.present? %>
                <%= image_tag(@product.image.thumb.url)%>
            <% else %>
                <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
            <% end %>
        </div>
        <div style="height:100px;">
            <%= @product.description%>
        </div>
        <div >
            数量：  <%= @product.quantity%>
        </div>
        <div >
            ¥<%= @product.price %>
        </div>
        <div class="pull-right">
            <% if @product.quantity.present? && @product.quantity > 0 %>
                <%= link_to("加入购物车", add_to_cart_product_path(@product), method: :post, class: "btn btn-primary btn-lg btn-danger")%>
            <% else %>
                销售一空，无法购买
            <% end %>
        </div>
    </div>
</div>