config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords'
    }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :products do
        member do
            post :add_to_cart
        end
    end
    namespace :admin do
        resources :infos
        resources :products
        resources :orders do
            member do
                post :cancel
                post :ship
                post :shipped
                post :return
            end
        end
    end
    root 'welcome#index'
    resources :infos do
        resources :posts
    end
    resources :posts
    resources :carts do
        collection do
            delete :clean
            post :checkout
        end
    end
    resources :cart_items

    resources :orders do
        member do
            post :pay_with_alipay
            post :pay_with_wechat
            post :apply_to_cancel
        end
    end
    namespace :account do
        resources :orders
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :products, through: :cart_items, source: :product

    def add_product_to_cart(product)
        ci = cart_items.build
        ci.product = product
        ci.quantity = 1
        ci.save
    end

    def total_price
        sum = 0
        cart_items.each do |cart_item|
            if cart_item.product.price.present?
                sum += cart_item.quantity * cart_item.product.price
            end
        end
        sum
    end

    def clean!
        cart_items.destroy_all
    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
    belongs_to :cart
    belongs_to :product
end

app/models/info.rb
class Info < ApplicationRecord
    has_many :posts
    belongs_to :user, optional: true
end

app/models/information.rb
class Information < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
    before_create :generate_token

    def generate_token
        self.token = SecureRandom.uuid
    end
    has_many :productlists
    belongs_to :user
    validates :billing_name, presence: true
    validates :billing_address, presence: true
    validates :shipping_address, presence: true
    validates :shipping_name, presence: true

    scope :recent, -> { order('created_at DESC') }

    def set_payment_with!(method)
        update_columns(payment_method: method)
    end

    def pay!
        update_columns(is_paid: true)
    end

    include AASM

    aasm do
        state :order_placed, initial: true
        state :paid
        state :shipping
        state :shipped
        state :order_cancelled
        state :good_returned

        event :make_payment, after_commit: :pay! do
            transitions from: :order_placed, to: :paid
        end

        event :ship do
            transitions from: :paid, to: :shipping
        end

        event :deliver do
            transitions from: :shipping, to: :shipped
        end

        event :return_good do
            transitions from: :shipped, to: :good_returned
        end

        event :cancel_order do
            transitions from: [:order_placed, :paid], to: :order_cancelled
        end
    end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :info, optional: true
    belongs_to :user, optional: true
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/productlist.rb
class Productlist < ApplicationRecord
    belongs_to :order, optional: true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    def admin?
        is_admin
    end
    has_many :orders

    has_many :posts
    has_many :infos
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
    def render_cart_total_price(cart)
        cart.total_price
    end
end

app/helpers/flashes_helper.rb
module FlashesHelper
    FLASH_CLASSES = { alert: 'danger', notice: 'success', warning: 'warning' }.freeze
    def flash_class(key)
        FLASH_CLASSES.fetch key.to_sym, key
    end

    def user_facing_flashes
        flash.to_hash.slice 'alert', 'notice', 'warning'
    end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any?%>
    <% user_facing_flashes.each do |key,value|%>
        <div class="alert alert-dismissable alert-<%= flash_class(key)%>">
            <button class="close" data-dismiss="alert">x</button>
            <%= value %>
        </div>
    <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="text-center">
    <div class="footer-below">
        <p class="text-center"> ©2017 莱圳家园网
      <br>
            designed by YaoYiZhi
    </p >
    </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand " href="/">莱圳家园信息网</a>
        </div>
        <!--Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to carts_path do %>
                        购物车 <i class="fa fa-shopping-cart"><%= current_cart.products.count%></i>
                    <% end %>
                </li>
                <% if !current_user %>
                    <li><%=link_to("注册", new_user_registration_path)%></li>
                    <li><%=link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'), new_user_session_path)%></li>
                <% else %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Hi!, <%= current_user.email%>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to("个人订单列表", account_orders_path)%></li>
                            <% if current_user && current_user.admin?%>
                                <li><%=link_to("Admin Panel", admin_products_path)%></li>
                            <% end %>
                            <li><%= link_to(content_tag(:i, '登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete)%></li>
                        </ul>
                    </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>